runtimes/build.sh
runtimes/java-16/Dockerfile
src/Runtimes/Runtimes.php
tests/Runtimes/RuntimesTest.php

Upgrading to use new docker hub repositories

Upgrading to use new docker hub repositories

---

runtimes/build.sh
runtimes/dart-2.14/Dockerfile
src/Runtimes/Runtimes.php

* Fix dart runtimes using old docker hub runtimes image
* Add dart 2.14 runtime

Feat-dart-new-runtimes-and-fix

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Add issue template forms

---

runtimes/build.sh
runtimes/node-17.0/Dockerfile
src/Runtimes/Runtimes.php

Feat-node-17

---

runtimes/build.sh
runtimes/dart-2.15/Dockerfile
runtimes/ruby-3.1/Dockerfile
src/Runtimes/Runtimes.php

Feat-new-runtimes

---

src/Runtimes/Runtimes.php

Depends: https://github.com/open-runtimes/open-runtimes/pull/77 to be released to pass the test

new runtimes

---

src/Runtimes/Runtimes.php
tests/Runtimes/RuntimesTest.php

- Updates to use the new runtimes
- https://github.com/open-runtimes/open-runtimes/pull/74
YES

Update the runtimes

---

.travis.yml
composer.json
composer.lock

Bumps up a library version to be compatible dependency of Appwrite
x
Yes

Feat: Increase lib version

---

src/Runtimes/Runtimes.php

Adds bun image as supported in Appwrite.
* https://github.com/open-runtimes/open-runtimes/pull/195
Yes

Feat: Add Bun

---

src/Runtimes/Runtimes.php

Relies on this being successful: https://github.com/open-runtimes/open-runtimes/runs/17745996518

Feat: Add Dart 3.1

---

src/Runtimes/Runtimes.php

Adds support for Go runtime.
x
Yes

Feat: Add Go runtime

---

src/Runtimes/Runtimes.php

Uses helper start command, so those commands arent duplicated in multiple places
None (already tested in OPR/OPR)
https://github.com/open-runtimes/open-runtimes/pull/291/
yes

Feat: helper start command

---

src/Runtimes/Runtimes.php

Corrects base images, and adds newly supported runtimes by OPR
None
x
Yes

Feat: New runtimes

---

src/Runtimes/Runtimes.php

Removes minor version where  they arent supposed to be
Runtimes match on Docker hub:
- https://hub.docker.com/r/openruntimes/node/tags?name=v4-22
- https://hub.docker.com/r/openruntimes/java/tags?name=v4-22
x
Yes

Fix: node & java minor versions

---

composer.json
composer.lock

chore: update utopia-php/system to 0.9.0

---

src/Runtimes/Runtimes.php

Feat: Add static runtime

---

src/Runtimes/Runtimes.php

fix: static version

---

composer.lock
pint.json
src/Runtimes/Runtimes.php

Adds newly release Open Runtimes Flutter image
None
x
Yes

Feat: Add flutter

---

src/Runtimes/Runtimes.php

Add SSR runtime

---

src/Runtimes/Runtimes.php

Feat: Python 3.12 ML

---

src/Runtimes/Runtimes.php

Removes SSR, all it's features are now in Node runtime

Remove SSR

---

src/Runtimes/Runtimes.php

Add: Latest flutter

---

src/Runtimes/Runtimes.php

Chore: Update flutter versions

---

src/Runtimes/Runtimes.php

Switches from sh to bash
None needed
x
Yes

Feat: Add bash support

---

src/Runtimes/Runtimes.php

- add Flutter 3.32
- add Dart 3.8
- Existing tests
- https://github.com/open-runtimes/open-runtimes/pull/388
YES

Feat: Flutter 3.32 and Dart 3.8
